name : "Postman Collection Workflow"

on:
  push:
    branches: [main]
  workflow_dispatch:   
  schedule:
    - cron: 30 02 * * * # 8 am IST Everyday
    - cron: 00 14 * * * # 730 pm IST Everyday
    - cron: 00 06 * * 1-5 # 1130 pm IST Monday to Friday


    
    
    
    
