name: "Postman Collection Workflow"

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'   # 8 am IST Everyday
    - cron: '00 14 * * *'   # 7:30 pm IST Everyday
    - cron: '00 06 * * 1-5' # 11:30 pm IST Monday to Friday

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Nodejs and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Install newman and html-extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the postman collection with newman
        run: |
          newman run "Inwarranty-flow Collection.postman_collection.json" \
            -e "QA.postman_environment.json" \
            -d "testData.csv" \
            -r cli,htmlextra
