name : "Postman Collection Workflow"

on:
  push:
    branches: [main]
  workflow_dispatch:   
  schedule:
    - cron: 30 02 * * * # 8 am IST Everyday
    - cron: 00 14 * * * # 730 pm IST Everyday
    - cron: 00 06 * * 1-5 # 1130 pm IST Monday to Friday


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      -name: checkout the code
       uses: actions/checkout@v4.2.2

      -name: Install node.js and npm
       uses: actions/setup-node@v3.9.1
        with:
          node-versions:'22'
      
      -name: Install newman and html-extra globally
       run: npm install -g newman && npm install -g newman-reporter-htmlextra

      -name: Run the postman collection with newman
       run: |
            newman run 'Inwarranty-flow Collection.postman_collection.json'\
            -e QA.postman_environment.json\
            -d testData.csv\
            -r cli,htmlextra

   

      

          


    
    
    
    
